version: "3.8"

services:
  web:
    build:
      dockerfile: Dockerfile

    image: docker101-web

    ports:
      - "3002:3002"

    environment:
      - ENVIRONMENT=production

    volumes:
      - .:/app
